### ISSUE TITLE
Убрать синий контур, когда нажимаешь на инструктора и сделать почту активной

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#10]
![221212](https://user-images.githubusercontent.com/33779023/32979088-c1e8af18-cc5f-11e7-8b56-7a334b8e289b.png)

Сделать почту активной, чтобы пользователь сразу мог перейти в свою почту для написания письма инструктуру

**Comment by afrolovskiy** [comment]
Разложил изменения

**Comment by AlexanderFrolovskiy** [comment]
Не работают почты

**Comment by afrolovskiy** [comment]
работают. после нажатия открывается outlook или подобная программа.
