### ISSUE TITLE
Добавить раздел партнеры

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#11]
![default](https://user-images.githubusercontent.com/33779023/32979159-34159e60-cc61-11e7-9fe3-097438a6b08f.png)
![logo](https://user-images.githubusercontent.com/33779023/32979160-34333a4c-cc61-11e7-83cd-a7be1e2aca71.png)

В разделе Партнеры расположить данные логотипы, со временем будут добавляться

**Comment by AlexanderFrolovskiy** [comment]
https://www.mos.ru/widgets/citynews/#samples
![partner_utemplate](https://user-images.githubusercontent.com/33779023/32979244-89eac71a-cc62-11e7-9a51-ef5e5dc75e70.png)

Добавить этот логотип в разделы партнеры
Чтобы они в одну строчку получились рядом. Слова Правительство москвы можно убрать. просто соединить сам логотип и маленький информационный блок

**Comment by afrolovskiy** [comment]
@AlexanderFrolovskiy  Где расположить раздел (после какого раздела)?

**Comment by AlexanderFrolovskiy** [comment]
после отзывов

**Comment by afrolovskiy** [comment]
Добавил раздел Партнеры

**Comment by afrolovskiy** [comment]
Забыл про логитип "Спортивная Росия". Добавь его.

**Comment by AlexanderFrolovskiy** [comment]
Сделай логотип "Правительства Москвы" в таком виде
![img_20171201_085613_583](https://user-images.githubusercontent.com/33779023/33517226-9d5de75e-d799-11e7-8784-fcae79fa1516.jpg)


и добавь "Спортивную Россию"

![](https://user-images.githubusercontent.com/33779023/32979159-34159e60-cc61-11e7-9fe3-097438a6b08f.png)

**Comment by AlexanderFrolovskiy** [comment]
![image](https://user-images.githubusercontent.com/33779023/33517285-be847e4c-d79a-11e7-971b-9f0a79c813b6.png)

В верхнее меню не добавил раздел "Партнеры"

**Comment by afrolovskiy** [comment]
@AlexanderFrolovskiy Посмотри плс, если норм, то задачу закрою.

**Comment by afrolovskiy** [comment]
AlexanderFrolovskiy, [Dec 20, 2017 at 10:51:09 AM]:
Виджет на телефоне не открывается
А можешь местами поменять, чтобы спортивная Россия была по середине

**Comment by AlexanderFrolovskiy** [comment]
Добавить в раздел партнеры
![action-lab_new11-05](https://user-images.githubusercontent.com/33779023/34249725-c9b62af8-e64b-11e7-9c75-a670862afa79.png)

и сделать активную ссылку на их сайт, при нажатии на картинку
www.action-lab.ru

**Comment by AlexanderFrolovskiy** [comment]
На РЭУ: https://www.rea.ru/
на спортивную Россию: http://infosport.ru/

**Comment by afrolovskiy** [comment]
Сделал.
@AlexanderFrolovskiy Можешь плз посмотреть. Норм?

**Comment by AlexanderFrolovskiy** [comment]
Отлично, давай только вот эту бегающую строку от правительство москвы уберем - не смотрится... Достаточно логотипа будет. 
И получается, что при переходе они с нашего сайта уходят, давай сделаем, чтобы новая вкладка открывалась при переходе, а наша страничка оставалась

**Comment by afrolovskiy** [comment]
Убрал виджет правительства Москвы.

**Comment by afrolovskiy** [comment]
Из партнёров логотип правительства Москвы тоже убери) и сделай, пожалуйста, логотипы поменьше

**Comment by afrolovskiy** [comment]
Из партнёров логотип правительства Москвы тоже убери) и сделай, пожалуйста, логотипы поменьше

**Comment by afrolovskiy** [comment]
@AlexanderFrolovskiy Из партнёров убрал логотип правительства Москвы и сделад  логотипы поменьше

**Comment by AlexanderFrolovskiy** [comment]
Закрывай!)
