### ISSUE TITLE
Не работает выбор тренера при создании группы

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#12]
![image](https://user-images.githubusercontent.com/33779023/33003132-d2f3d25e-cdc9-11e7-897c-f825ea2675a5.png)

Когда щелкаешь выбрать тренера, ничего не происходит...

**Comment by afrolovskiy** [comment]
Разложил изменения

**Comment by AlexanderFrolovskiy** [comment]
Закрывай)
