### ISSUE TITLE
изменить название

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#15]
![image](https://user-images.githubusercontent.com/33779023/33178286-be56e28c-d076-11e7-9000-5b4c305eea5b.png)

Назвать "Номер договора" и "Дата договора"

**Comment by afrolovskiy** [comment]
Поправил.
@AlexanderFrolovskiy посмотри плз

**Comment by AlexanderFrolovskiy** [comment]
закрывай
