### ISSUE TITLE
баг при нажатии на карандашик

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#17]
![image](https://user-images.githubusercontent.com/33779023/33330884-1cc4582e-d471-11e7-8843-dd1e5eea242a.png)

В разделе куда вписываешь оплата при нажатии на карандашик, ничего не происходит. Видимо не введена форма записи и дальнейшее действие, только экран немного меркнет.

**Comment by afrolovskiy** [comment]
@AlexanderFrolovskiy  Починил
