### ISSUE TITLE
Добавить в контакты

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#18]
![image](https://user-images.githubusercontent.com/33779023/33517254-49081d36-d79a-11e7-9c6e-95f17167fce8.png)

Сделай телефон и почту размеров с иконки, а то их вообще не видно, и получается это единственное место где вообще это дерьмо все написано.
Еще под телефоном добавь, пожалуйста:
(с понедельника по пятницу с 10:00 до 14:00)

**Comment by AlexanderFrolovskiy** [comment]
и справа от телефона добавить логотип наш
![logo](https://user-images.githubusercontent.com/33779023/33517467-2a9440a6-d79e-11e7-830a-0c6017e51c04.png)

**Comment by afrolovskiy** [comment]
Сделал.
@AlexanderFrolovskiy Посмотри плс норм или нет?

**Comment by AlexanderFrolovskiy** [comment]
![image](https://user-images.githubusercontent.com/33779023/34142841-862b6904-e49a-11e7-8794-aa6b544a903f.png)
Лех, а пихни ее в самый нижний правый угол и чутка побольше сделай.
И такое ощущение, что шрифт везде разный( сделай как-нибудь по равномернее его

Бассейны давай уберем: филиал и Динамо, че то по ним ничего не идет пока(((

**Comment by afrolovskiy** [comment]
@AlexanderFrolovskiy Поправил

**Comment by AlexanderFrolovskiy** [comment]
закрывай)
