### ISSUE TITLE
Добавить отзыв

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#26]
![image](https://user-images.githubusercontent.com/33779023/34812363-69eb422c-f6b6-11e7-9a35-392dc71f58ed.png)

![t3_nkxqedbs](https://user-images.githubusercontent.com/33779023/34812364-6db2ac92-f6b6-11e7-9fd6-75a560873ca5.jpg)

Только посмотри, чтобы по размеру с остальными совпадал, если будет больше, то сокращай прям по последним предложениям

**Comment by afrolovskiy** [comment]
Добавил. Влез целиком)

**Comment by afrolovskiy** [comment]
@AlexanderFrolovskiy посмотри плз
