### ISSUE TITLE
добавить обозначения в строки оплаты

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#37]
![image](https://user-images.githubusercontent.com/33779023/37251292-6e446010-251e-11e8-9463-f180da8980ac.png)

Надо добавить обозначения:
1) болеет

другие потом придумаю

**Comment by afrolovskiy** [comment]
Добавил . @AlexanderFrolovskiy  глянь плз

**Comment by AlexanderFrolovskiy** [comment]
2. не ходил
3. перенос

и выбранный пункт не отображается потом в общей таблице, а если 0 стереть и оставить только выбранный пункт, то выпадает ошибка
![image](https://user-images.githubusercontent.com/33779023/37563711-1e60983c-2a98-11e8-83ec-ed7813fcae07.png)

**Comment by afrolovskiy** [comment]
Добавил новые пункты и поправил ошибку. @AlexanderFrolovskiy глянь плз.

**Comment by afrolovskiy** [comment]
Убрал карандашики при наличии записи. Добавил метку "нет". В дальнейшем, если понадобится, мб переделать на кнопку удалить.
