### ISSUE TITLE
Добавить в раздел "Наша Деятельность" подраздел ГТО

### ISSUE THREAD

**Issue by afrolovskiy** [afrolovskiy/akvant#7]
Третий значок, без рамки который. Глянь, как он выглядеть будет на фоне других, подойдёт или нет.

![gto](https://user-images.githubusercontent.com/2668736/32688170-fd94a798-c6dc-11e7-8520-dff505f93be1.png)

![gto1](https://user-images.githubusercontent.com/2668736/32688171-fdb7843e-c6dc-11e7-99d4-a8e0e422cdd5.png)

![gto2](https://user-images.githubusercontent.com/2668736/32688172-fdd72ae6-c6dc-11e7-9cf1-71f4182ec2f7.png)

Текст:
```
Выполнение нормативов ГТО
- подготовка к выполнению нормативов
- организация выполнения нормативов и получения знака 
```

Оформить раздел "Наша Деятельность" в 2 колонки.

**Comment by afrolovskiy** [comment]
![unnamed](https://user-images.githubusercontent.com/2668736/32720323-47b4084e-c874-11e7-8f26-fe9e95fb0f20.png)

**Comment by AlexanderFrolovskiy** [comment]
Закрывай задачу)
