### ISSUE TITLE
Добавить отзыв на промо страницу

### ISSUE THREAD

**Issue by afrolovskiy** [afrolovskiy/akvant#8]
только текст немного поменять надо, там ошибка:

...За инициативность, подкреплеННУЮ профессионализмом ...

![55](https://user-images.githubusercontent.com/2668736/32829685-db9ed4e0-ca03-11e7-896b-8f390ef889e5.png)

![xp0jl_qx-40](https://user-images.githubusercontent.com/2668736/32829686-dbb9ed0c-ca03-11e7-9d09-67a45b36db5a.jpg)

**Comment by afrolovskiy** [comment]
Разложил изменения

**Comment by AlexanderFrolovskiy** [comment]
можешь закрывать
