### ISSUE TITLE
Изменить комментарий

### ISSUE THREAD

**Issue by AlexanderFrolovskiy** [afrolovskiy/akvant#9]
![1111](https://user-images.githubusercontent.com/33779023/32979073-67db7f0a-cc5f-11e7-8aff-f799aa716223.png)

Убрать выделенную строчку, чтобы поле не скакало....

**Comment by afrolovskiy** [comment]
Разложил изменения

**Comment by AlexanderFrolovskiy** [comment]
Можешь закрывать
